#!/bin/sh

#
# Copyright 2017 Warlock <internalmike@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

author_name="Warlock"
author_email="internalmike@gmail.com"
author_git="A1-Triard"

help() {
    echo "Usage: hnew [OPTION]... LIB_NAME APP_NAME"
    echo "Create new haskell project."
    echo ""
    echo "  -h          display this help and exit"
    echo "  -d DESCR    description"
    echo "  -g URL.git  attach to github project"
    echo "  -f          do NOT format cabal file"
    echo "  -p          do NOT create Geany project file"
    echo "  -l          use LIB_NAME as project name instead of APP_NAME"
}

error() {
    echo 'Try `hnew -h'"'"' for more information.' >&2
}

no_dup() {
    if [ -n "$1" ]; then
        echo "Duplicated option: -$2" >&2
        error
        exit 1
    fi
}

github_url=''
descr=''
format_cabal="yes"
create_project="yes"
library="no"

while getopts ":hg:d:fpl" opt; do
    case $opt in
    h)
        help
        exit 0
        ;;
    f)
        format_cabal="no"
        shift
        ;;
    p)
        create_project="no"
        shift
        ;;
    l)
        library="yes"
        shift
        ;;
    g)
        no_dup "$github_url" g || exit 1
        github_url="$OPTARG"
        if [ -z "$github_url" ]; then
            echo "Empty URL" >&2
            error
            exit 1
        fi
        shift
        shift
        ;;
    d)
        no_dup "$descr" d || exit 1
        descr="$OPTARG"
        shift
        shift
        ;;
    \?)
        echo "Invalid option: -$OPTARG" >&2
        error
        exit 1
        ;;
    esac
done
if [ ".$1" = ".--" ]; then
    shift
fi

lib_name="$1"
app_name="$2"

if [ -z "$lib_name" ]; then
    echo "Empty library name" >&2
    error
    exit 1
fi

if [ -z "$app_name" ]; then
    echo "Empty application name" >&2
    error
    exit 1
fi

if [ ".$library" = ".yes" ]; then
    project_name="$lib_name"
else
    project_name="$app_name"
fi

if [ -e "$project_name" ]; then
    echo "Directory exists: $project_name" >&2
    exit 1
fi

echo "GitHub repository: $github_url"
echo "Project name: $project_name"
echo "Library name: $lib_name"
echo "Application name: $app_name"
echo "Decsription: $descr"
echo ""
while true; do
    read -p "Continue? " yn
    case $yn in
        [Yy]*) break;;
        [Nn]*) exit;;
        *) echo "Please answer yes or no.";;
    esac
done

if [ -n "$github_url" ]; then
    gitdir=$(mktemp -d hnew.XXXXXX)
    git clone "$github_url" $gitdir || { rm -rf $gitdir ; exit 1 }
fi

tempdir=$(mktemp -d hnew.XXXXXX)
cd $tempdir

stack new "$lib_name" \
    -p author-email:"$author_name <$author_email>" \
    -p author-name:"$author_name <$author_email>" \
    -p github-username:"$author_git" \
    -p category:"CLI" \
    -p copyright:"$(date +%Y) $author_name <$author_email>" \
    || { cd .. ; rm -rf $gitdir ; rm -rf $tempdir ; exit 1 }
cd ..
mv "$tempdir/$lib_name" "$project_name" || { rm -rf $gitdir ; rm -rf $tempdir ; exit 2 }
rmdir $tempdir || { rm -rf $gitdir ; rm -rf $tempdir ; exit 2 }

if [ -n "$github_url" ]; then
    mv $gitdir/.git "$project_name" || { rm -rf $gitdir ; exit 2 }
    rm -rf $gitdir
fi

cd "$project_name"
cat > .gitignore << "EOF"
*~
*.test
*.lkshs
*.geany
dist
cabal-dev
*.o
*.hi
*.chi
*.chs.h
*.dyn_o
*.dyn_hi
.hpc
.hsenv
.cabal-sandbox/
cabal.sandbox.config
*.prof
*.aux
*.hp
.stack-work/
EOF

if [ -z "$github_url" ]; then
    git init || exit 2
fi
git add . || exit 2
git submodule add https://github.com/A1-Triard/haskell_include.git include || exit 2

cp -f include/LICENSE . || exit 2
git add LICENSE || exit 2

sed -i "s/$lib_name-exe/$app_name/g" "$lib_name.cabal"
sed -i "s/$lib_name-test/$project_name-test/g" "$lib_name.cabal"
sed -i "s/license:             BSD3/license:             Apache/" "$lib_name.cabal"
sed -i "s/extra-source-files:  README.md/-- extra-source-files:/" "$lib_name.cabal"
sed -i "s/version:             0.1.0.0/version:             0.1/" "$lib_name.cabal"

if [ -n "$github_url" ]; then
    github_project="$(dirname "$github_url")/$(basename "$github_url" .git)"
    sed -i "s|https://github.com/A1-Triard/$lib_name|$github_project|g" "$lib_name.cabal"
fi

if [ -n "$descr" ]; then
    sed -i "s/-- synopsis:/synopsis: $descr/" "$lib_name.cabal"
    sed -i "s/-- description:/description: $descr/" "$lib_name.cabal"
fi

cat > extensions << "EOF"
  default-extensions: BangPatterns
                    , CPP
                    , DataKinds
                    , DefaultSignatures
                    , DeriveDataTypeable
                    , DeriveGeneric
                    , DeriveFoldable
                    , DeriveTraversable
                    , EmptyCase
                    , EmptyDataDecls
                    , ExistentialQuantification
                    , ExplicitForAll
                    , FlexibleContexts
                    , FlexibleInstances
                    , GADTs
                    , GeneralizedNewtypeDeriving
                    , KindSignatures
                    , LambdaCase
                    , LiberalTypeSynonyms
                    , MagicHash
                    , MonadComprehensions
                    , MultiParamTypeClasses
                    , MultiWayIf
                    , NegativeLiterals
                    , OverloadedStrings
                    , ParallelListComp
                    , PatternSynonyms
                    , RankNTypes
                    , ScopedTypeVariables
                    , StandaloneDeriving
                    , TemplateHaskell
                    , TransformListComp
                    , TypeFamilies
                    , TypeOperators
                    , UnboxedTuples
                    , UnicodeSyntax
                    , ViewPatterns
EOF

cat > include_dirs << "EOF"
  include-dirs: include
EOF

cat > lib_options << "EOF"
  ghc-options: -fmax-pmcheck-iterations=100000000 -O2 -Wall -Werror -fno-warn-unused-imports -fprint-potential-instances
EOF

cat > exe_options << "EOF"
  ghc-options: -threaded -rtsopts -with-rtsopts=-N -fmax-pmcheck-iterations=100000000 -O2 -Wall -Werror -fno-warn-unused-imports -fprint-potential-instances
EOF

cat > language << "EOF"
  default-language: Haskell2010
EOF

lib_params=$(cat extensions include_dirs lib_options language)
exe_params=$(cat extensions include_dirs exe_options language)

rm -f extensions include_dirs lib_options exe_options language

tmp=$(mktemp hnew.XXXXXX)
awk -v LP="$lib_params" -v EP="$exe_params" '
    BEGIN {
        first = 1
    } {
        if($0 == "  default-language:    Haskell2010") {
            if(first) {
                first = 0
                print LP
            } else {
                print EP
            }
        } else if($0 != "  ghc-options:         -threaded -rtsopts -with-rtsopts=-N") {
            print
        }
    }
    ' "$lib_name.cabal" > $tmp
mv -f $tmp "$lib_name.cabal"

tmp=$(mktemp hnew.XXXXXX)
awk '
    BEGIN {
        test = 0
    } {
        add = 0
        if($0 == "  main-is:             Spec.hs") {
            test = 1
        } else if ($0 == "  build-depends:       base") {
            if(test)
                add = 1
        }
        print
        if(add)
            print "                     , HUnit"
    }
    ' "$lib_name.cabal" > $tmp
mv -f $tmp "$lib_name.cabal"

if [ ".$format_cabal" = ".yes" ]; then
    tmp=$(mktemp hnew.XXXXXX)
    awk '
        {
            if(match($0, "^ *, ")) {
                sub("^ *", "")
                for(i = 0; i < colon_column - 1; ++i)
                    $0 = " " $0
            } else {
                sub(":  +", ": ")
                colon_column = index($0, ":")
            }
            print
        }
        ' "$lib_name.cabal" > $tmp
    mv -f $tmp "$lib_name.cabal"
fi

git add . || exit 2
git commit -m "Empty project" || exit 2

if [ ".$create_project" = ".yes" ]; then
    cat > "$project_name.geany" << "EOF"
[editor]
line_wrapping=false

[file_prefs]
final_new_line=true
ensure_convert_new_lines=true
strip_trailing_spaces=true
replace_tabs=true

[indentation]
indent_width=2
indent_type=0
indent_hard_tab_width=8
detect_indent=true
detect_indent_width=true
indent_mode=2

[project]
base_path=.
EOF
    echo "name=$project_name" >> "$project_name.geany"
fi
